--- !ruby/object:Jumpstart::Configuration
application_name: My New App
background_job_processor: sidekiq
cancel_immediately: '1'
email_provider: sendgrid
omniauth_providers:
- :facebook
- :github
- :twitter
payment_processors:
- :stripe
- :paypal
plans:
  - name: Basic
    frequency: monthly
    stripe_id: basic-monthly
    amount: 29
    features:
      - Feature 1
      - Feature 2
      - Feature 3
  - name: Basic
    frequency: yearly
    stripe_id: basic-yearly
    amount: 290
    features:
      - Feature 1
      - Feature 2
      - Feature 3

  - name: Advanced
    frequency: monthly
    stripe_id: advanced-monthly
    amount: 29
    features:
      - Feature 1
      - Feature 2
      - Feature 3
  - name: Advanced
    frequency: yearly
    stripe_id: advanced-yearly
    amount: 290
    features:
      - Feature 1
      - Feature 2
      - Feature 3
