!ruby/object:Jumpstart::Configuration
application_name: My New App
omniauth_providers:
  - :facebook
  - :github
payment_processor:
  stripe: false
  braintree: true
plans:
  - id: default
    name: Default
    price: 1000
    stripe_id: default
