--- !ruby/object:Jumpstart::Configuration
application_name: My New App
background_job_processor: sidekiq
cancel_immediately: '1'
email_provider: sendgrid
omniauth_providers:
- :facebook
- :github
- :twitter
payment_processors:
- :stripe
- :paypal
