--- !ruby/object:Jumpstart::Configuration
application_name: My New App
email_provider: sendgrid
omniauth_providers:
- :facebook
- :github
payment_processors:
- :stripe
- :paypal
cancel_immediately: '1'
