--- !ruby/object:Jumpstart::Configuration
application_name: Jumpstart
business_name: Jumpstart Company, LLC
domain: example.com
support_email: support@example.com
default_from_email: Jumpstart <support@example.com>
payment_processors:
- :stripe
- :paypal
omniauth_providers:
- facebook
- github
- google-oauth2
- twitter
